#include "Samples.hpp"

#include "../../data/samples/laser_01.wav.h"
#include "../../data/samples/laser_02.wav.h"
#include "../../data/samples/laser_03.wav.h"
#include "../../data/samples/laser_04.wav.h"

#include "../../data/samples/alarm_reverb.wav.h"
#include "../../data/samples/dirty_syren_01.wav.h"
#include "../../data/samples/dirty_syren_02.wav.h"

#include "../../data/samples/low_tone_01.wav.h"
#include "../../data/samples/low_tone_02.wav.h"
#include "../../data/samples/low_tone_03.wav.h"
#include "../../data/samples/low_tone_04.wav.h"
#include "../../data/samples/low_tone_05.wav.h"

#include "../../data/samples/high_tone_01.wav.h"
#include "../../data/samples/high_tone_02.wav.h"
#include "../../data/samples/high_tone_03.wav.h"
#include "../../data/samples/high_tone_04.wav.h"
#include "../../data/samples/high_tone_05.wav.h"

#include "../../data/samples/alien_voice_01.wav.h"
#include "../../data/samples/alien_voice_02.wav.h"
#include "../../data/samples/alien_voice_03.wav.h"
#include "../../data/samples/alien_voice_04.wav.h"

#include "../../data/samples/new/alien_voice_101.wav.h"
#include "../../data/samples/new/alien_voice_102.wav.h"
#include "../../data/samples/new/alien_voice_103.wav.h"
#include "../../data/samples/new/alien_voice_201.wav.h"
#include "../../data/samples/new/alien_voice_202.wav.h"
#include "../../data/samples/new/alien_voice_301.wav.h"
#include "../../data/samples/new/alien_voice_302.wav.h"
#include "../../data/samples/new/alien_voice_303.wav.h"
#include "../../data/samples/new/alien_voice_401.wav.h"

#include "../../data/samples/new/alien_voice_r_101.wav.h"
#include "../../data/samples/new/alien_voice_r_102.wav.h"
#include "../../data/samples/new/alien_voice_r_103.wav.h"
#include "../../data/samples/new/alien_voice_r_201.wav.h"
#include "../../data/samples/new/alien_voice_r_202.wav.h"
#include "../../data/samples/new/alien_voice_r_301.wav.h"
#include "../../data/samples/new/alien_voice_r_302.wav.h"
#include "../../data/samples/new/alien_voice_r_303.wav.h"
#include "../../data/samples/new/alien_voice_r_401.wav.h"

#include "../../data/samples/morse_letter_s.wav.h"
#include "../../data/samples/morse_letter_o.wav.h"
