#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

#define DEBUG_SERIAL

#ifdef DEBUG_SERIAL

// #define DEBUG_SERIAL_MORE_DATA

#endif

#define BUTTON_MODE_INVERSE

#define START_LED_ANIMATION_TYPE LED_ANIMATION_TYPE_SCANNER
#define START_SEVEN_SEGMENT_ANIMATION_TYPE SEVEN_SEGMENT_ANIMATION_TYPE_MESSAGE_1

#endif // COMMON_DEFINES_H
