#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

#define DEBUG_SERIAL

#ifdef DEBUG_SERIAL

// #define DEBUG_SERIAL_MORE_DATA

#endif

#define BUTTON_MODE_INVERSE

#define START_LED_ANIMATION_TYPE LED_ANIMATION_TYPE_SCANNER
#define START_LED_ANIMATION_DELAY 100

#define START_SEVEN_SEGMENT_ANIMATION_TYPE SEVEN_SEGMENT_ANIMATION_TYPE_MESSAGE_1
#define START_SEVEN_SEGMENT_ANIMATION_DELAY 300

#define DEFAULT_LED_ANIMATION_TYPE START_LED_ANIMATION_TYPE
#define DEFAULT_LED_ANIMATION_DELAY START_LED_ANIMATION_DELAY

#define DEFAULT_SEVEN_SEGMENT_ANIMATION_TYPE START_SEVEN_SEGMENT_ANIMATION_TYPE
#define DEFAULT_SEVEN_SEGMENT_ANIMATION_DELAY START_SEVEN_SEGMENT_ANIMATION_DELAY

// External button PIN SETTINGS
#define EXTERNAL_BUTTON1_PIN 11
#define EXTERNAL_BUTTON2_PIN 12
#define EXTERNAL_BUTTON3_PIN 13
#define EXTERNAL_BUTTON4_PIN 14
#define EXTERNAL_BUTTON5_PIN 15

// TM1638 (model 1) module PIN SETTINGS
#define TM1638_STROBE_PIN 4 // strobe
#define TM1638_CLOCK_PIN 6  // clock
#define TM1638_DIO_PIN 7    // data

// Stereo DAC module PCM5102A PIN SETTINGS
#define DAC_I2S_BCK_PIN 26  // bit clock
#define DAC_I2S_LRCK_PIN 27 // left right clock
#define DAC_I2S_DATA_PIN 28 // data in

#endif // COMMON_DEFINES_H
